# Generated by Django 4.2.2 on 2023-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='memo',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Intermediate'), (4, 'Challenging'), (5, 'Difficult')], default=3),
        ),
    ]
